definitions:
  models.Transport:
    properties:
      bicycl:
        type: string
      drive:
        type: string
      transit:
        type: string
      walk:
        type: string
    type: object
info:
  contact: {}
paths:
  /transports/:
    get:
      consumes:
      - application/json
      description: Get transports
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Transport'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get transports
swagger: "2.0"
