import React from 'react';
import Head from 'next/head';

import Header from '../components/Header';
import ListView from './view/list';
import MapView from './view/map';

import { useAppSelector, useAppDispatch } from '../store/hook';
import { change } from '../store/slices/viewSlice';

export default function Home() {
  const [listView, setListView] = React.useState<boolean>(true);
  const view = useAppSelector(state => state.view.value);
  const dispatch = useAppDispatch();

  function handleClick() {
    setListView(!listView);
    dispatch(change()); 
  }

  return (
    <>
        <Head>
            <title>EpicRoadTrip | Welcome !</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'/>
            <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'/>
        </Head>
        <Header />
        { view ? <p>List</p> : <p>Map</p>}
        <button onClick={() => {handleClick()}} style={{position: 'absolute', bottom: '5%', left: '50%', transform: 'translateX(-50%)'}}>Change view</button>
    </>
  )
}