import React from 'react';
import Header from '../components/Header';
import Head from 'next/head';
import { useRouter } from 'next/navigation';

export default function Home() {
  const router = useRouter();
  const [type, setType] = React.useState<string>('list');

  React.useEffect(() => {
    if (router.asPath !== '/?type=list' && router.asPath !== '/?type=map') {
      router.push('/?type=list');
    } else {
      setType(router.query.type);
    }
  }, [router]);

  let content;
  if (type === 'list') {
    content = <div>Contenu de la liste</div>;
  } else if (type === 'map') {
    content = <div>Contenu de la carte</div>;
  } else {
    content = <div>Chargement...</div>;
  }
  return (
    <>
        <Head>
            <title>EpicRoadTrip | Welcome !</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'/>
            <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'/>
        </Head>
        <Header />
        <div>{content}</div>
    </>
  )
}