name: Go Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_directory:
          ["accommodation", "bar", "event", "photo", "restaurant", "transport"]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - name: Check out code
        uses: actions/checkout@v3

      - name: Compile Go code
        run: |
          cd back/${{ matrix.go_directory }}
          go mod tidy
          go build -v -o my_binary

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.go_directory }}-binary
          path: ${{ matrix.go_directory }}/
