name: Code coverage backend
on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop
jobs:
  coverage:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.1' # The Go version to download (if necessary) and use.
      - run: go version

      - run: go test -coverprofile coverage.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: backend
