# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - epicroadtrip

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://epicroadtrip.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dcdc7910ee374e69a70375d9cb8279d4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_67d380342ce246f29459e4862a1198ab }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: epicroadtrip.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dcdc7910ee374e69a70375d9cb8279d4 }}/backend:${{ github.sha }}
        file: ./back/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'epicroadtrip'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a4848043cc03446d9e8c275d4237fad0 }}
        images: 'epicroadtrip.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dcdc7910ee374e69a70375d9cb8279d4 }}/backend:${{ github.sha }}'
