# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - epicroadtrip

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4eb0596e1c37489497961c0e84842fd7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_36bef4aa121042b49f17e8ed8c04db70 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4eb0596e1c37489497961c0e84842fd7 }}/backend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'epicroadtrip'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cf950880073c499d865e51063c4777c5 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4eb0596e1c37489497961c0e84842fd7 }}/backend:${{ github.sha }}'