# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - epicroadtrip

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://epicroadtrip.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_eacd5e8b67d54f97899b59abcd428d24 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_57081c06190148c59052d32d2fd86aa1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: epicroadtrip.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_eacd5e8b67d54f97899b59abcd428d24 }}/back:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'epicroadtrip'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ebb11968d1ec48528c5d3824da80d88b }}
        images: 'epicroadtrip.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_eacd5e8b67d54f97899b59abcd428d24 }}/back:${{ github.sha }}'