name: Code coverage
on:
  push:
  pull_request:
jobs:
  coverage:
  
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./front
    
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 7.28.0
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]
      
      - run: ls -lah
      
      - run: pnpm run test --coverage
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      
