name: Tests backend
on:
  [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.1'
      - run: go version

      - run: go test
